src/main/scala/parsley/internal/deepembedding/DeepEmbedding.scala
Factored out all the common code for binary ast nodes
=> Refactor - Binary AST Node Refactor

src/main/scala/parsley/Result.scala, src/test/scala/parsley/ResultTests.scala
This adds a bunch of additional helpers and support to Result
=> Added extra methods to Result

src/main/scala/parsley/Parsley.scala, src/main/scala/parsley/internal/deepembedding/IntrinsicEmbedding.scala, src/test/scala/parsley/CoreTests.scala
These combinators are not only useful in their own right, but will also be handy to make use of the untyped registers that are likely to become idiomatic for a while with #26 before 2.1. Complements #28.
=> Added collect and cast combinators

src/main/scala/parsley/internal/deepembedding/IntrinsicEmbedding.scala, src/main/scala/parsley/internal/instructions/Context.scala, src/main/scala/parsley/internal/instructions/IntrinsicInstrs.scala, src/test/scala/parsley/CoreTests.scala
Implements the Parsley Haskell style semantics as per #26
=> Updated to new semantics, still need the rollback combinator

src/main/scala/parsley/Parsley.scala, src/main/scala/parsley/internal/instructions/Context.scala
Added a way from parsing straight from a file: this changes the error messages to reference the filename
=> Added parseFromFile

.github/workflows/ci.yaml, .github/workflows/release.yaml
Add on workflow_dispatch event for ci and release workflows
=> Add check-duplicate job in ci workflow

.github/workflows/ci.yaml, .github/workflows/release.yaml
Specific matrix jobs are required, skipping whole matrix messes up requirements
=> Skip individual steps in validate

src/main/scala/parsley/internal/deepembedding/Parsley.scala, src/main/scala/parsley/internal/deepembedding/PrimitiveEmbedding.scala, src/main/scala/parsley/internal/deepembedding/SequenceEmbedding.scala, src/main/scala/parsley/internal/instructions/Context.scala, src/main/scala/parsley/internal/instructions/CoreInstrs.scala, src/main/scala/parsley/internal/instructions/IntrinsicInstrs.scala, src/main/scala/parsley/internal/instructions/OptInstrs.scala, src/test/scala/parsley/ErrorMessageTests.scala
Removed the old code for errors from the machine.
=> Remove old errors

src/main/scala/parsley/internal/deepembedding/IntrinsicEmbedding.scala, src/main/scala/parsley/internal/deepembedding/PrimitiveEmbedding.scala, src/main/scala/parsley/internal/instructions/Context.scala, src/main/scala/parsley/internal/instructions/CoreInstrs.scala, src/main/scala/parsley/internal/instructions/ErrorInstrs.scala, src/main/scala/parsley/internal/instructions/Errors.scala, src/main/scala/parsley/internal/instructions/IntrinsicInstrs.scala, src/main/scala/parsley/internal/instructions/OptInstrs.scala, src/main/scala/parsley/internal/instructions/TokenStringInstrs.scala, src/main/scala/parsley/token/Lexer.scala
Added explanations to error messages, with a combinator yet to be released. Improved some of the error messages in lexer
=> Improvements to Error Messages

src/main/scala/parsley/Parsley.scala, src/main/scala/parsley/internal/deepembedding/IntrinsicEmbedding.scala, src/main/scala/parsley/internal/deepembedding/PrimitiveEmbedding.scala, src/main/scala/parsley/internal/instructions/IntrinsicInstrs.scala, src/main/scala/parsley/internal/instructions/OptInstrs.scala, src/test/scala/parsley/CharTests.scala, src/test/scala/parsley/CoreTests.scala
Added `guardAgainst` and `filterOut`, and deprecated `>?>` (to become `filter` one day) and `guardNot`.
=> Filtering rework

src/main/scala/parsley/internal/instructions/TokenInstrs.scala, src/test/scala/parsley/TokeniserTests.scala
Fixes some off logic in the Comment instruction that means multi-line comments are required.
=> Dodgy comment

README.md, src/main/rootdoc.md, src/main/scala/parsley/Parsley.scala, src/main/scala/parsley/io.scala, src/main/scala/parsley/unsafe.scala, src/test/scala/parsley/CharTests.scala, src/test/scala/parsley/CombinatorTests.scala, src/test/scala/parsley/CoreTests.scala, src/test/scala/parsley/ErrorMessageTests.scala, src/test/scala/parsley/ExpressionParserTests.scala, src/test/scala/parsley/TokeniserTests.scala, src/test/scala/parsley/internal/InternalTests.scala
modified the parser API, breaking into IO and non-IO, as well as adding a Try wrapper to parseFromFile. runParser -> parse.
=> Parser API Changes

src/main/scala/parsley/Parsley.scala, src/main/scala/parsley/internal/deepembedding/IntrinsicEmbedding.scala, src/main/scala/parsley/internal/deepembedding/Parsley.scala, src/main/scala/parsley/internal/deepembedding/SelectiveEmbedding.scala, src/main/scala/parsley/internal/machine/instructions/IntrinsicInstrs.scala, src/test/scala/parsley/CoreTests.scala
Adds the missing `<+>` combinator, and makes `branch` first class, no longer relying on the slow `>>=` based implementation.
=> Sum parser

src/main/scala/parsley/internal/deepembedding/AlternativeEmbedding.scala, src/main/scala/parsley/internal/deepembedding/TokenEmbedding.scala, src/main/scala/parsley/token/Lexer.scala, src/test/scala/parsley/TokeniserTests.scala
Fixed #95 by excluding case-insensitive Specific nodes from tablification
=> Case-insensitive alternative fix.

src/main/scala/parsley/registers.scala, src/test/scala/parsley/CoreTests.scala
Improves the inference qualities of the register API by making the combinators methods on registers instead of functions.
=> Improved register API

.github/workflows/ci.yaml, build.sbt, project/plugins.sbt
Bump the versions of Java, Node and LLVM tested against in CI, as well as bumps to scala versions and scala-js and scala-native versions.
=> CI and Scala version bumps

src/main/scala/parsley/internal/machine/Context.scala, src/main/scala/parsley/internal/machine/instructions/IntrinsicInstrs.scala, src/test/scala/parsley/CharTests.scala
Removed some redundant code, and fixed a bug in the `StringTok` offset adjusters. Added more tests.
=> Position improvements

src/main/scala/parsley/Parsley.scala
=> Added lazy-right hand sides to `<~` and `~>`

src/main/scala/parsley/character.scala, src/main/scala/parsley/internal/deepembedding/backend/AlternativeEmbedding.scala, src/main/scala/parsley/internal/deepembedding/backend/ErrorEmbedding.scala, src/main/scala/parsley/internal/deepembedding/backend/GeneralisedEmbedding.scala, src/main/scala/parsley/internal/deepembedding/backend/IntrinsicEmbedding.scala, src/main/scala/parsley/internal/deepembedding/backend/IterativeEmbedding.scala, src/main/scala/parsley/internal/deepembedding/backend/PrimitiveEmbedding.scala, src/main/scala/parsley/internal/deepembedding/backend/SelectiveEmbedding.scala, src/main/scala/parsley/internal/deepembedding/backend/SequenceEmbedding.scala, src/main/scala/parsley/internal/deepembedding/backend/StrictParsley.scala, src/main/scala/parsley/internal/deepembedding/frontend/LazyParsley.scala, src/main/scala/parsley/internal/machine/Context.scala, src/main/scala/parsley/internal/machine/instructions/CoreInstrs.scala, src/main/scala/parsley/internal/machine/instructions/ErrorInstrs.scala, src/main/scala/parsley/internal/machine/instructions/IntrinsicInstrs.scala, src/main/scala/parsley/internal/machine/instructions/IterativeInstrs.scala, src/main/scala/parsley/internal/machine/instructions/OptInstrs.scala, src/main/scala/parsley/internal/machine/instructions/PrimitiveInstrs.scala, src/main/scala/parsley/internal/machine/stacks/ArrayStack.scala, src/test/scala/parsley/StringTests.scala, src/test/scala/parsley/internal/InternalTests.scala
Cleaned up and reworked some of the instructions, improving performance, fixing bugs and improving the naming. Still to be done will be reorganising the files, but that can wait for a while. Also fixes #118
=> Instruction rework

build.sbt, parsley/shared/src/main/scala/parsley/internal/deepembedding/backend/AlternativeEmbedding.scala, parsley/shared/src/main/scala/parsley/internal/deepembedding/singletons/TokenEmbedding.scala, parsley/shared/src/main/scala/parsley/internal/deepembedding/singletons/token/SymbolEmbedding.scala, parsley/shared/src/main/scala/parsley/internal/machine/Context.scala, parsley/shared/src/main/scala/parsley/internal/machine/instructions/IntrinsicInstrs.scala, parsley/shared/src/main/scala/parsley/internal/machine/instructions/TokenInstrs.scala, parsley/shared/src/main/scala/parsley/internal/machine/instructions/token/CharPredicate.scala, parsley/shared/src/main/scala/parsley/internal/machine/instructions/token/SymbolInstrs.scala, parsley/shared/src/main/scala/parsley/token/predicate.scala, parsley/shared/src/main/scala/parsley/token/symbol/ConcreteSymbol.scala, parsley/shared/src/test/scala/parsley/token/symbol/SymbolTests.scala
Added an generalised form of SoftKeyword to handle both unicode, basic, and not required
=> Optimised `softKeyword`

parsley/shared/src/main/scala/parsley/internal/deepembedding/backend/SequenceEmbedding.scala
Backport to 4.1 series for #156, detailed in #157
=> Backport fix for #156

parsley/shared/src/main/scala/parsley/internal/deepembedding/backend/SequenceEmbedding.scala
=> Backport #162

parsley/shared/src/main/scala/parsley/internal/collection/immutable/Trie.scala, parsley/shared/src/main/scala/parsley/internal/deepembedding/singletons/token/SymbolEmbedding.scala, parsley/shared/src/main/scala/parsley/internal/deepembedding/singletons/token/TextEmbedding.scala, parsley/shared/src/main/scala/parsley/internal/machine/instructions/token/SymbolInstrs.scala, parsley/shared/src/main/scala/parsley/internal/machine/instructions/token/TextInstructions.scala, parsley/shared/src/main/scala/parsley/token/descriptions/TextDesc.scala, parsley/shared/src/main/scala/parsley/token/text/Escape.scala
This patch aims to improve the performance of string and character literals in the Lexer by making escape character handling into a single instruction. This will in turn be used by any future optimisations of string and characters.
=> Optimised Escape Characters in String and Character Literals

parsley/shared/src/main/scala/parsley/internal/machine/instructions/DebugInstrs.scala
replace carriage return character ("\r") in debug combinator with a green arrow (←).
=> handles carriage returns in debug

.github/workflows/ci.yml, build.sbt, parsley/shared/src/main/scala/parsley/combinator.scala, parsley/shared/src/main/scala/parsley/internal/deepembedding/backend/StrictParsley.scala, parsley/shared/src/main/scala/parsley/internal/machine/instructions/PrimitiveInstrs.scala, parsley/shared/src/main/scala/parsley/registers.scala, parsley/shared/src/test/scala/parsley/CoreTests.scala
=> Backport 4.1/166 bug flatmap doesnt allocation space for registers except for the first time it executes

parsley/shared/src/main/scala/parsley/internal/deepembedding/backend/IterativeEmbedding.scala, parsley/shared/src/main/scala/parsley/internal/machine/Context.scala, parsley/shared/src/main/scala/parsley/internal/machine/instructions/IterativeInstrs.scala, parsley/shared/src/test/scala/parsley/CombinatorTests.scala, parsley/shared/src/test/scala/parsley/token/SpaceTests.scala
=> Backport 4.1/167 bug iterative combinators revive dead hints

parsley/shared/src/main/scala/parsley/internal/machine/instructions/DebugInstrs.scala
=> Backported debug fixes with carriage return

README.md, parsley/shared/src/main/scala/parsley/internal/errors/ParseError.scala, parsley/shared/src/main/scala/parsley/internal/machine/Context.scala, parsley/shared/src/main/scala/parsley/internal/machine/errors/DefuncBuilders.scala, parsley/shared/src/main/scala/parsley/internal/machine/errors/DefuncError.scala, parsley/shared/src/main/scala/parsley/internal/machine/errors/DefuncHints.scala, parsley/shared/src/main/scala/parsley/internal/machine/instructions/IterativeInstrs.scala
=> Backport 4.1/various error related bugs

build.sbt, parsley/shared/src/main/scala/parsley/Parsley.scala, parsley/shared/src/main/scala/parsley/character.scala, parsley/shared/src/main/scala/parsley/errors/DefaultErrorBuilder.scala, parsley/shared/src/main/scala/parsley/errors/helpers.scala, parsley/shared/src/main/scala/parsley/token/errors/ErrorConfig.scala, project/plugins.sbt
Exposes a bunch of the functionality with the `DefaultErrorBuilder` as standalone functions to allow for their reuse in other implementations. Closes #202
=> Exposed `DefaultErrorBuilder` helpers

project/ParsleySitePlugin.scala
I added the `css` folder, so it will pick up everything in it, which is just one file atm.
=> add explicit configuration for custom CSS

.github/workflows/ci.yml, README.md, build.sbt, parsley/shared/src/main/scala/parsley/internal/deepembedding/backend/SequenceEmbedding.scala, parsley/shared/src/main/scala/parsley/internal/deepembedding/backend/StrictParsley.scala, parsley/shared/src/main/scala/parsley/internal/deepembedding/frontend/LazyParsley.scala, parsley/shared/src/main/scala/parsley/internal/machine/instructions/CoreInstrs.scala, parsley/shared/src/main/scala/parsley/internal/machine/instructions/PrimitiveInstrs.scala, parsley/shared/src/main/scala/parsley/registers.scala, parsley/shared/src/test/scala/parsley/CoreTests.scala, project/build.properties, project/plugins.sbt
Backports #248 to 4.5, fixing #241 properly.
=> #248 Backport

docs/api-guide/generic.md
=> fix(doc): scala tuple size desc

docs/api-guide/expr/precedence.md, parsley/js/rootdoc.md, parsley/shared/src/main/scala/parsley/token/Lexer.scala, parsley/shared/src/main/scala/parsley/token/numeric/LexemeCombined.scala, parsley/shared/src/main/scala/parsley/token/numeric/LexemeInteger.scala
=> Found typos and additional whitespace
