j-mie6/parsley

build.sbt
src/main/scala-0.27/parsley/XCompat.scala
src/main/scala/parsley/Cont.scala
src/main/scala/parsley/Parsley.scala
src/main/scala/parsley/package.scala
src/test/scala/parsley/CharTests.scala
src/test/scala/parsley/CombinatorTests.scala
src/test/scala/parsley/CoreTests.scala
src/test/scala/parsley/ErrorMessageTests.scala
src/test/scala/parsley/ExpressionParserTests.scala
src/test/scala/parsley/ParsleyTest.scala
src/test/scala/parsley/TokeniserTests.scala

We use `-source:3.0-migration` in order to cross build between Scala 2 and Dotty.

Cross build for Dotty-0.27.0-RC1

---

src/main/scala/parsley/instructions/CoreInstrs.scala

The debug context was broken because of an errant `toString` after fixing the deprecated toCharSequence.

Fixed dodgy toString in debug combinator

---

README.md
src/main/scala/parsley/Parsley.scala
src/main/scala/parsley/Token.scala
src/test/scala/parsley/CoreTests.scala
src/test/scala/parsley/TokeniserTests.scala

Added `foldRight1` and `foldLeft1` combinators using them to parse naturals in `Token`, fixing #37.

Added non-empty parser fold variants

---

src/main/scala/parsley/combinator.scala

This fixes #54, however it makes the decide combinator much slower in the two argument case. We need to optimise `branch` for this to be ok again!

semantic preserving fix for decide

---

.gitignore
src/main/scala/parsley/internal/deepembedding/GeneralisedEmbedding.scala
src/main/scala/parsley/internal/instructions/Context.scala

When the same sub parser is used and compiled by two separate threads, it can result in a race condition involving the error relabeling mechanism. Marking the `letFinder` as synchronized appears to fix this (I've also marked `ready` as sychronized just in case). I suspect there is a more deep cause to this issue, and there is a better fix, but this will do for now. It's not even that expensive either.

Added synchronisation to AST

---

src/main/scala-2.12/parsley/XCompat.scala
src/main/scala/parsley/expr/Fixity.scala
src/main/scala/parsley/internal/deepembedding/GeneralisedEmbedding.scala
src/main/scala/parsley/internal/deepembedding/Parsley.scala
src/main/scala/parsley/internal/deepembedding/PrimitiveEmbedding.scala
src/main/scala/parsley/internal/instructions/CoreInstrs.scala
src/test/scala/parsley/internal/InternalTests.scala

This PR properly addresses the thread-safety bug with multiple threads processing a shared sub-parser. This removes the hot patches implemented in #57 and properly repairs the issue by disconnecting let-finding and preprocess passes. The let-finding no longer uses any mutability, instead thread-safe Scala lazy vals are used. The preprocess pass then creates an entirely new version of the AST where mutation is allowed again (this work is repeated for each thread).
In addition, this PR has improved let-binding analysis to allow for factoring out of parsers with common bodies _and_ common error messages and also ensures that parsers that appear multiple times but don't share error messages are not factored out in the first place. This improves performance in general, potentially by …

Fully thread-safe AST

---

src/main/scala/parsley/implicits.scala

Added 22 inverted application lifts, this can be helpful to make Scala's inference perform better.
The name `map` is provisional and may be deprecated in favour of a new name until Parsley 3, when it may be replaced. Other naming candidates include `lift` and `ap`.

Higher-arity Map

---

src/main/scala/parsley/implicits.scala
src/main/scala/parsley/lift.scala

The lift functions all have `by-name` parameters, fixing #63. `map` family (to be called `zipWith`) does not, because they are strict tuples. If necessary this can be done, however, the `lift` family and `map` are in a one-to-one correspondence.

Added lazy annotations to lifts, but not maps

---

src/main/scala/parsley/Parsley.scala
src/main/scala/parsley/internal/deepembedding/PrimitiveEmbedding.scala
src/main/scala/parsley/internal/instructions/Context.scala
src/main/scala/parsley/internal/instructions/ErrorInstrs.scala
src/main/scala/parsley/internal/instructions/Errors.scala
src/main/scala/parsley/token/Lexer.scala

Added the explain combinator, which can be used to annotate an error with a reason that the error occured. Unlike labels, these reasons will not materialise as hints if the error was recovered from.

Explain combinator

---

src/main/scala/parsley/internal/instructions/IntrinsicInstrs.scala
src/test/scala/parsley/CombinatorTests.scala
src/test/scala/parsley/CoreTests.scala

Fixes #70. Also correctly removes the unexpected message from filters to properly align with the expected behaviour of `empty`, which is the advertised semantics.

`filterOut` should not pop stack after failure

---

src/main/scala/parsley/Parsley.scala
src/main/scala/parsley/internal/instructions/Context.scala
src/main/scala/parsley/internal/instructions/Errors.scala
src/main/scala/parsley/internal/instructions/IntrinsicInstrs.scala
src/main/scala/parsley/internal/instructions/TokenInstrs.scala
src/main/scala/parsley/internal/instructions/TokenNumericInstrs.scala
src/main/scala/parsley/internal/instructions/TokenStringInstrs.scala
src/main/scala/parsley/unsafe.scala

Changes the implementation for the input from `Array[Char]` to `String`. Any (negligible) performance gains once obtained are now dwarfed by the use of `Array.slice` (O(n)) as opposed to `String.substring` (O(1)). Also, this allows us to remove a couple of `StringBuilders` in the tokeniser, as now `substring` can be used. A definitely performance gain was obtained from this.

String vs array

---

src/main/scala/parsley/Parsley.scala
src/main/scala/parsley/internal/deepembedding/GeneralisedEmbedding.scala
src/main/scala/parsley/internal/errors/Builders.scala
src/main/scala/parsley/internal/errors/DefuncHints.scala
src/main/scala/parsley/internal/errors/Errors.scala
src/main/scala/parsley/internal/machine/Context.scala
src/main/scala/parsley/internal/machine/errors/Builders.scala
src/main/scala/parsley/internal/machine/errors/DefuncError.scala
src/main/scala/parsley/internal/machine/errors/DefuncHints.scala
src/main/scala/parsley/internal/machine/instructions/CoreInstrs.scala
src/main/scala/parsley/internal/machine/instructions/ErrorInstrs.scala
src/main/scala/parsley/internal/machine/instructions/IntrinsicInstrs.scala
src/main/scala/parsley/internal/machine/instructions/OptInstrs.scala
src/main/scala/parsley/internal/machine/stacks/ErrorStack.scala
src/main/scala/parsley/internal/machine/stacks/HintStack.scala
src/test/scala/parsley/internal/machine/errors/DefuncErrorTests.scala
src/test/scala/parsley/internal/machine/errors/DefuncHintsTests.scala
src/test/scala/parsley/internal/machine/errors/MockedBuilders.scala

This pull request will implement a variety of optimisations purely concerning the evaluation of the defunctionalised forms for error messages and hints. As an example, indices of the components of the hints that have currently made it into the result of evaluation can be recorded to ensure that recomputation isn't done, as well as ensure that hints that will never make it to the final result are not computed.
This PR _may_ also introduce a CPS transformation to ensure stack-safe evaluation. But I'm not yet convinced this will be needed: most parsers seem to produce smaller defunctionalised terms purely based on the small pieces of information used to prune away the defunctionalised forms in the main machine.

Optimised defunc evaluation

---

src/main/scala/parsley/internal/deepembedding/AlternativeEmbedding.scala
src/main/scala/parsley/internal/errors/Errors.scala
src/main/scala/parsley/internal/machine/Context.scala
src/main/scala/parsley/internal/machine/errors/DefuncError.scala
src/main/scala/parsley/internal/machine/instructions/IntrinsicInstrs.scala
src/main/scala/parsley/internal/machine/instructions/OptInstrs.scala
src/main/scala/parsley/internal/machine/instructions/TokenInstrs.scala
src/main/scala/parsley/internal/machine/instructions/TokenStringInstrs.scala
src/test/scala/parsley/internal/machine/errors/DefuncErrorTests.scala
src/test/scala/parsley/internal/machine/errors/DefuncHintsTests.scala

Added better unexpected messages to lexer instructions, allowed JumpTable to have better unexpected messages, cut unexpected messages short at first newline OR space

Improvements to Lexer Errors and Errors in General

---

.github/workflows/ci.yaml
.github/workflows/release.yaml
build.sbt

The CI for the Scala-JS support is now up and running, and tests against node 14 LTS and 15. Scala 2.12 and Scala 2.13 now will have releases for Scala-JS Parsley.

Scala-JS CI + Publish

---

src/main/scala/parsley/expr/chain.scala
src/main/scala/parsley/expr/precedence.scala
src/test/scala/parsley/ExpressionParserTests.scala
src/test/scala/parsley/internal/InternalTests.scala

Adds in a new curried form of monolithic `precedence` and introduced `postfix1` and `prefix1` combinators to `chain`, which have a more general type as a result of how they work.

Parsley 3 expr

---

.github/workflows/ci.yaml
build.sbt
jvm/src/main/scala/parsley/io.scala
native/src/main/scala/parsley/io.scala
project/plugins.sbt
src/main/rootdoc.md
src/main/scala/parsley/Parsley.scala
src/main/scala/parsley/Result.scala
src/main/scala/parsley/errors/ErrorBuilder.scala
src/main/scala/parsley/errors/combinator.scala
src/main/scala/parsley/errors/revisions.scala
src/main/scala/parsley/internal/errors/Builders.scala
src/main/scala/parsley/internal/errors/ErrorItem.scala
src/main/scala/parsley/internal/errors/ParseError.scala
src/main/scala/parsley/internal/machine/Context.scala
src/main/scala/parsley/registers.scala
src/main/scala/parsley/token/Lexer.scala
src/main/scala/parsley/unsafe.scala
src/test/scala/parsley/CharTests.scala
src/test/scala/parsley/CombinatorTests.scala
src/test/scala/parsley/CoreTests.scala
src/test/scala/parsley/ErrorTests.scala
src/test/scala/parsley/ExpressionParserTests.scala
src/test/scala/parsley/TokeniserTests.scala

This PR introduces a new package for errors in the base, as well as a new error builder so that users can change the formatting of the errors in a uniform way. This functionality is currently subject to alterations, as I want to make the API a little easier to extend and use.

Parsley 3 errors

---

src/main/scala-2.12/parsley/XCompat.scala
src/main/scala-2.13+/parsley/XCompat.scala
src/main/scala/parsley/expr/Fixity.scala
src/main/scala/parsley/expr/Levels.scala
src/main/scala/parsley/expr/Ops.scala
src/main/scala/parsley/expr/chain.scala
src/main/scala/parsley/expr/precedence.scala
src/test/scala/parsley/ExpressionParserTests.scala

This introduces some improvements to the `GOps` mechanism, making the precedence table reversible, and removing the redundant empty level. Additionally, I've added in an `SOps` object, which improves the inference for subtyped ASTs previously making use of `GOps`. Operators using `Prefix` and `Postfix` now avoid wrapping when only an upcast is required. 
Added `NonAssoc` fixity, which allows for non-chain precedence table.

Parsley 3 Precedence Enhancements

---

js/src/test/scala/parsley/internal/machine/errors/DefuncErrorTests.scala
jvm/src/test/scala/parsley/internal/machine/errors/DefuncErrorTests.scala
native/src/test/scala/parsley/internal/machine/errors/DefuncErrorTests.scala
src/main/scala/parsley/errors/DefaultErrorBuilder.scala
src/main/scala/parsley/errors/combinator.scala
src/main/scala/parsley/internal/deepembedding/ErrorEmbedding.scala
src/main/scala/parsley/internal/deepembedding/GeneralisedEmbedding.scala
src/main/scala/parsley/internal/deepembedding/PrimitiveEmbedding.scala
src/main/scala/parsley/internal/machine/Context.scala
src/main/scala/parsley/internal/machine/errors/DefuncError.scala
src/main/scala/parsley/internal/machine/errors/DefuncStates.scala
src/main/scala/parsley/internal/machine/instructions/ErrorInstrs.scala
src/test/scala/parsley/ErrorTests.scala

Added the `amend` and `entrench` combinators, which work as a pair to correct (and prevent correction) of error messages in special circumstances.

Error offset correctors

---

src/main/scala-2.12/parsley/XCompat.scala
src/main/scala-2.13+/parsley/XCompat.scala
src/main/scala-2.x/parsley/expr/Ops.scala
src/main/scala-3.x/parsley/expr/Ops.scala
src/main/scala/parsley/expr/Fixity.scala
src/main/scala/parsley/expr/Levels.scala
src/main/scala/parsley/expr/Ops.scala
src/main/scala/parsley/expr/chain.scala
src/main/scala/parsley/expr/precedence.scala
src/test/scala/parsley/ExpressionParserTests.scala

Simplifies the API based on knowledge gained from the Design Patterns of Parser Combinators work. Adds an extra parameter to the chains, which helps inference on Scala 3 and In some cases on Scala 2, but is more painful if things do go wrong. Removed redundant parameters in the precedence framework and improved inference massively for Scala 3.

Parsley 4 expression simplification

---

src/main/scala-2.12/parsley/WithFilter.scala
src/main/scala/parsley/Parsley.scala
src/main/scala/parsley/character.scala
src/main/scala/parsley/combinator.scala
src/main/scala/parsley/errors/combinator.scala
src/main/scala/parsley/expr/chain.scala
src/main/scala/parsley/implicits/lift.scala
src/main/scala/parsley/internal/deepembedding/AlternativeEmbedding.scala
src/main/scala/parsley/internal/deepembedding/ErrorEmbedding.scala
src/main/scala/parsley/internal/deepembedding/GeneralisedEmbedding.scala
src/main/scala/parsley/internal/deepembedding/IntrinsicEmbedding.scala
src/main/scala/parsley/internal/deepembedding/IterativeEmbedding.scala
src/main/scala/parsley/internal/deepembedding/PrimitiveEmbedding.scala
src/main/scala/parsley/internal/deepembedding/SelectiveEmbedding.scala
src/main/scala/parsley/internal/deepembedding/SequenceEmbedding.scala
src/main/scala/parsley/lift.scala
src/main/scala/parsley/registers.scala
src/main/scala/parsley/token/Lexer.scala
src/test/scala/parsley/CoreTests.scala

Parsley has always been lazy in all combinators, including receivers. This allows for recursive parsers to be defined. However, the receivers of all combinators, as well as leading edges for all function combinators can be made strict: if they are recursive in the left-most position, this is left-recursion, which is illegal. This PR makes left-recursion into undefined behaviour, and Parsley no longer guards against it so readily. This does affect the order in which parsers must be with respect to forward-referencing, however. It should provide a performance boost for cold parsers, simplifies the user API, and allows for better implicit conversions.

Strict API

---

src/main/scala/parsley/character.scala
src/test/scala/parsley/CharTests.scala

It would be nice to be able to write `oneOf('a' to 'z')`... now you can!

Added range-based char class operations `oneOf` and `noneOf`

---

src/main/scala/parsley/Parsley.scala
src/main/scala/parsley/combinator.scala
src/main/scala/parsley/expr/infix.scala
src/main/scala/parsley/expr/mixed.scala
src/main/scala/parsley/expr/precedence.scala
src/main/scala/parsley/implicits/zipped.scala
src/main/scala/parsley/internal/deepembedding/IterativeEmbedding.scala
src/test/scala/parsley/ExpressionParserTests.scala

This breaks out the existing chain API into both `chain` and `infix` which corresponds more closely to the DPfPC presentation and allows for better QoL when using the homogenous chains.
Also adds the mixed-chain combinators `mixed.left1` and `mixed.right1`. These will need to be integrated into the precedence table in due course.

Reshuffled Chains

---

src/main/scala/parsley/internal/machine/instructions/TokenInstrs.scala
src/test/scala/parsley/TokeniserTests.scala

When no comments are specified for a `LanguageDef`, whitespace consumption enters an infinite loop, since it does not update the program counter when the spaces have been consumed.

Fixed infinite loop in whitespace with no comments in `LanguageDef`

---

src/main/scala/parsley/internal/machine/Context.scala

The multiRet functionality used to drop multiple call frames on return does not properly decrement the depth count unless each return is a "hard return". This is masked by stateful instructions and the operation of Parsley 3, but you can never be too sure.

Added missing depth decrement to multiRet

---

src/main/scala-2.x/parsley/internal/deepembedding/Cont.scala
src/main/scala-3.x/parsley/internal/deepembedding/Cont.scala
src/main/scala/parsley/internal/LinkedList.scala
src/main/scala/parsley/internal/collection/mutable/DoublyLinkedList.scala
src/main/scala/parsley/internal/collection/mutable/Radix.scala
src/main/scala/parsley/internal/collection/mutable/SinglyLinkedList.scala
src/main/scala/parsley/internal/deepembedding/backend/AlternativeEmbedding.scala
src/main/scala/parsley/internal/deepembedding/backend/ErrorEmbedding.scala
src/main/scala/parsley/internal/deepembedding/backend/GeneralisedEmbedding.scala
src/main/scala/parsley/internal/deepembedding/backend/IntrinsicEmbedding.scala
src/main/scala/parsley/internal/deepembedding/backend/IterativeEmbedding.scala
src/main/scala/parsley/internal/deepembedding/backend/PrimitiveEmbedding.scala
src/main/scala/parsley/internal/deepembedding/backend/SelectiveEmbedding.scala
src/main/scala/parsley/internal/deepembedding/backend/SequenceEmbedding.scala
src/main/scala/parsley/internal/deepembedding/backend/StrictParsley.scala
src/main/scala/parsley/internal/deepembedding/frontend/AlternativeEmbedding.scala
src/main/scala/parsley/internal/deepembedding/frontend/ErrorEmbedding.scala
src/main/scala/parsley/internal/deepembedding/frontend/GeneralisedEmbedding.scala
src/main/scala/parsley/internal/deepembedding/frontend/IntrinsicEmbedding.scala
src/main/scala/parsley/internal/deepembedding/frontend/IterativeEmbedding.scala
src/main/scala/parsley/internal/deepembedding/frontend/LazyParsley.scala
src/main/scala/parsley/internal/deepembedding/frontend/PrimitiveEmbedding.scala
src/main/scala/parsley/internal/deepembedding/frontend/SelectiveEmbedding.scala
src/main/scala/parsley/internal/deepembedding/frontend/SequenceEmbedding.scala
src/main/scala/parsley/internal/deepembedding/singletons/Singletons.scala
src/main/scala/parsley/internal/machine/instructions/IterativeInstrs.scala
src/main/scala/parsley/internal/machine/instructions/TokenInstrs.scala
src/main/scala/parsley/internal/machine/instructions/TokenStringInstrs.scala
src/main/scala/parsley/internal/machine/stacks/Stack.scala
src/main/scala/parsley/token/Lexer.scala

Both chains of `<|>` and chains of `<*`/`*>` can be converted into a normal form which flattens the structure. This has some benefits, as re-association no longer needs to be performed, which was previously O(n^2). Now the normalisation can occur in O(n) time.

AST Normalisation

---

jvm-native/src/main/scala/parsley/io.scala
src/main/scala/parsley/Parsley.scala
src/main/scala/parsley/internal/deepembedding/backend/PrimitiveEmbedding.scala
src/main/scala/parsley/internal/deepembedding/backend/SequenceEmbedding.scala
src/main/scala/parsley/internal/deepembedding/backend/StrictParsley.scala
src/main/scala/parsley/internal/deepembedding/frontend/LazyParsley.scala
src/main/scala/parsley/internal/deepembedding/frontend/PrimitiveEmbedding.scala
src/main/scala/parsley/internal/machine/Context.scala
src/main/scala/parsley/internal/machine/instructions/PrimitiveInstrs.scala
src/main/scala/parsley/registers.scala
src/test/scala/parsley/CoreTests.scala

This lifts the existing limit of 4 registers in simultaneous use, closing #33. It introduces new combinators for creating fresh registers during parse and also ensures the register array is correctly sized to accommodate more than (or less than) 4 registers.
It consists of the following work items:

Lifting register restriction

---

src/main/scala/parsley/internal/machine/instructions/TokenInstrs.scala
src/main/scala/parsley/token/Lexer.scala
src/test/scala/parsley/TokeniserTests.scala

Fixes #126: the logic doesn't advance the instruction counter when no comment could be read but the shared prefix of the comment starts could: when this is the empty string, this causes problems.

Ensure that comments without shared prefix do not loop indefinitely

---

README.md
parsley/shared/src/main/scala/parsley/internal/errors/ParseError.scala
parsley/shared/src/main/scala/parsley/internal/machine/errors/DefuncBuilders.scala
parsley/shared/src/main/scala/parsley/internal/machine/instructions/DebugInstrs.scala

Persisted caret info from `NoItem` forward into `TrivialError` by using `Either` instead of `Option`

Fixed missing wider caret for unexpectedless trivial errors

---

README.md
parsley/shared/src/main/scala-2/parsley/internal/deepembedding/Cont.scala
parsley/shared/src/main/scala-3/parsley/internal/deepembedding/Cont.scala
parsley/shared/src/main/scala/parsley/Parsley.scala
parsley/shared/src/main/scala/parsley/internal/deepembedding/frontend/LazyParsley.scala

Parsley _previously_ used a `safeCall` mechanism to run the internal compiler in a stack-unsafe way and revert to a stack-safe version if it threw a `StackOverflowError`. This is not safe: this is a fatal error, and the JVM may be left in an inconsistent state after "recovery" and on Native a stack-overflow is undefined behaviour. Both not good things to be relying on. As such the automatic recovery has been removed: if a stack-overflow occurs before parsing begins then use `.overflows()` on the parser that is having `.parse` called on it to compile it in a stack-safe way. The same goes for users who wish to be immune from any potential stack-overflows full-stop.
Thanks to @armanbilge for letting me know!

Remove `StackOverflowError` catching, use explicit `overflows` instead

---

parsley/shared/src/main/scala/parsley/Parsley.scala
parsley/shared/src/main/scala/parsley/errors/tokenextractors/LexToken.scala
parsley/shared/src/main/scala/parsley/position.scala
parsley/shared/src/test/scala/parsley/ExpressionParserTests.scala
parsley/shared/src/test/scala/parsley/StringTests.scala

This adds a new `position` object to house the existing position functionality (deprecating the old functionality), and exposes a new `offset` combinator.

Improved `position` API

---

parsley/shared/src/main/scala/parsley/errors/combinator.scala
parsley/shared/src/test/scala/parsley/ErrorTests.scala

Deprecates the old `unexpected` and `!` combinators and adds in `unexpectedLegacy` for long-term support past 4.3.0. These combinators really don't do the right thing and will both be replaced by improved, but slightly different combinators moving forward.

Deprecate old error methods

---

build.sbt
parsley/shared/src/main/scala/parsley/errors/combinator.scala
parsley/shared/src/main/scala/parsley/errors/patterns.scala
parsley/shared/src/main/scala/parsley/internal/deepembedding/backend/ErrorEmbedding.scala
parsley/shared/src/main/scala/parsley/internal/deepembedding/backend/PrimitiveEmbedding.scala
parsley/shared/src/main/scala/parsley/internal/deepembedding/frontend/ErrorEmbedding.scala
parsley/shared/src/main/scala/parsley/internal/machine/instructions/ErrorInstrs.scala
parsley/shared/src/main/scala/parsley/token/errors/ConfigImplTyped.scala
parsley/shared/src/main/scala/parsley/token/errors/ErrorConfig.scala
parsley/shared/src/main/scala/parsley/token/errors/VerifiedAndPreventativeErrors.scala

Adds support for _Verified Errors_ combinators, to `parsley.errors.patterns`.

Error pattern combinators

---

parsley/shared/src/main/scala/parsley/character.scala
parsley/shared/src/main/scala/parsley/internal/deepembedding/backend/AlternativeEmbedding.scala
parsley/shared/src/main/scala/parsley/internal/deepembedding/backend/ErrorEmbedding.scala
parsley/shared/src/main/scala/parsley/internal/deepembedding/backend/SequenceEmbedding.scala
parsley/shared/src/main/scala/parsley/internal/deepembedding/singletons/IntrinsicEmbedding.scala
parsley/shared/src/main/scala/parsley/internal/deepembedding/singletons/PrimitiveEmbedding.scala
parsley/shared/src/main/scala/parsley/internal/machine/Context.scala
parsley/shared/src/main/scala/parsley/internal/machine/instructions/IntrinsicInstrs.scala
parsley/shared/src/main/scala/parsley/internal/machine/instructions/OptInstrs.scala
parsley/shared/src/main/scala/parsley/internal/machine/instructions/PrimitiveInstrs.scala
parsley/shared/src/main/scala/parsley/internal/machine/instructions/TokenInstrs.scala
parsley/shared/src/main/scala/parsley/internal/machine/instructions/TokenNumericInstrs.scala

Optimises the generic combinators used for unicode consumption: `satisfyUtf16` and `charUtf16`. The former was previously using a `flatMap`, so this should be a substantial improvement.

Optimised the general unicode combinators for `Lexer`

---

parsley/shared/src/main/scala/parsley/internal/deepembedding/backend/SequenceEmbedding.scala

Fixes #161, the normalisation that moves all pures to the end of a `Seq` node only fires if there is only one node in the "after" set, it should fire regardless.

Corrected sequence normalisation with `pure`

---

build.sbt
parsley/shared/src/main/scala/parsley/expr/Fixity.scala
parsley/shared/src/main/scala/parsley/expr/Ops.scala
parsley/shared/src/main/scala/parsley/expr/SmartOps.scala
parsley/shared/src/main/scala/parsley/expr/infix.scala
parsley/shared/src/main/scala/parsley/expr/precedence.scala

By defining extra private functional on the `Fixity` type itself, it is possible to avoid the `asInstanceOf` and pattern matching previously used to define the logic for precedence (namely, the casts in `GOps`)

Removed the type casts within the `expr` machinery

---

parsley/shared/src/main/scala/parsley/internal/errors/ParseError.scala
parsley/shared/src/main/scala/parsley/internal/machine/Context.scala
parsley/shared/src/main/scala/parsley/internal/machine/errors/DefuncBuilders.scala
parsley/shared/src/main/scala/parsley/internal/machine/errors/DefuncError.scala
parsley/shared/src/main/scala/parsley/internal/machine/errors/DefuncHints.scala
parsley/shared/src/main/scala/parsley/internal/machine/instructions/IterativeInstrs.scala

Fixed overwide carets in trivial errors, hints from adjusting unexpected size to 0, and hints from getting reborn during an iterative combinator.

Fixed various error bugs

---

parsley/shared/src/main/scala/parsley/character.scala

Added labels directly into the nodes in parsley.character, saving some allocation and work in backend for the in-built parsers.

Labelled `character` combinators

---

parsley/shared/src/main/scala/parsley/internal/errors/ParseError.scala

Due to capping of the caret at the end of the input line, carets focused on the EOF itself were not rendered. This increases that limit by 1, which allows carets to stretch one position over the end of the input line to EOF.

Fixed caret not appearing for EOF

---

build.sbt
parsley/shared/src/main/scala/parsley/character.scala
parsley/shared/src/main/scala/parsley/internal/deepembedding/singletons/token/TextEmbedding.scala
parsley/shared/src/main/scala/parsley/internal/errors/ErrorItem.scala
parsley/shared/src/main/scala/parsley/internal/machine/Context.scala
parsley/shared/src/main/scala/parsley/internal/machine/errors/DefuncError.scala
parsley/shared/src/main/scala/parsley/internal/machine/instructions/IterativeInstrs.scala
parsley/shared/src/main/scala/parsley/internal/machine/instructions/token/TextInstructions.scala
parsley/shared/src/main/scala/parsley/token/descriptions/TextDesc.scala
parsley/shared/src/main/scala/parsley/token/errors/ConfigImplTyped.scala
parsley/shared/src/main/scala/parsley/token/errors/ErrorConfig.scala
parsley/shared/src/main/scala/parsley/token/text/Escape.scala
parsley/shared/src/test/scala/parsley/token/descriptions/DescGen.scala
parsley/shared/src/test/scala/parsley/token/descriptions/DescShrink.scala
parsley/shared/src/test/scala/parsley/token/text/EscapeSemanticPreservationSpec.scala
parsley/shared/src/test/scala/parsley/token/text/EscapeTests.scala
parsley/shared/src/test/scala/parsley/token/text/OriginalEscape.scala
project/build.properties
project/plugins.sbt

The character mappings have been optimised, but not the numeric escapes: `atMost`, `exactly`, or `oneOfExactly`. This PR optimises these, which should decrease the size of text lexing a bunch

Optimised Numeric Escape Characters

---

parsley/shared/src/main/scala/parsley/errors/combinator.scala
parsley/shared/src/main/scala/parsley/internal/machine/Context.scala
parsley/shared/src/main/scala/parsley/internal/machine/errors/DefuncBuilders.scala
parsley/shared/src/main/scala/parsley/internal/machine/errors/DefuncError.scala
parsley/shared/src/main/scala/parsley/internal/machine/instructions/ErrorInstrs.scala
parsley/shared/src/test/scala/parsley/internal/machine/errors/DefuncErrorTests.scala

Implemented partial amending as described in #152, but not yet with the caret stretching behaviour: the combinators are not exposed until another minor release.

Partial Amending

---

build.sbt
parsley/shared/src/main/scala/parsley/errors/helpers.scala
parsley/shared/src/main/scala/parsley/errors/tokenextractors/LexToken.scala
parsley/shared/src/main/scala/parsley/errors/tokenextractors/MatchParserDemand.scala
parsley/shared/src/main/scala/parsley/errors/tokenextractors/SingleChar.scala
parsley/shared/src/main/scala/parsley/errors/tokenextractors/TillNextWhitespace.scala
parsley/shared/src/test/scala/parsley/ParsleyTest.scala
parsley/shared/src/test/scala/parsley/errors/TokenExtractorTests.scala

Slightly improved the rendering of unprintable characters, and unicode handling within the existing token extractors.
Now, `SingleChar` will always account for a code-point (no per character handling!) and the categories are more explicit with no more regex (which apparently is a little buggy on the JVM for this kind of thing!)

Improved Unicode handling in token extractors

---

.github/workflows/ci.yml
build.sbt
parsley/shared/src/main/scala/parsley/Parsley.scala
parsley/shared/src/main/scala/parsley/genericbridges.scala

Fixes #187. Adds the `as` combinator to alias `#>`, and additionally adds the symmetric `from` combinator to alias `<#` on the generic bridges.

Added "wordy" `as` and `from` combinators

---

parsley/shared/src/main/scala/parsley/internal/deepembedding/frontend/AlternativeEmbedding.scala
parsley/shared/src/main/scala/parsley/internal/deepembedding/frontend/ErrorEmbedding.scala
parsley/shared/src/main/scala/parsley/internal/deepembedding/frontend/IntrinsicEmbedding.scala
parsley/shared/src/main/scala/parsley/internal/deepembedding/frontend/IterativeEmbedding.scala
parsley/shared/src/main/scala/parsley/internal/deepembedding/frontend/LazyParsley.scala
parsley/shared/src/main/scala/parsley/internal/deepembedding/frontend/PrimitiveEmbedding.scala
parsley/shared/src/main/scala/parsley/internal/deepembedding/frontend/SelectiveEmbedding.scala
parsley/shared/src/main/scala/parsley/internal/deepembedding/frontend/SequenceEmbedding.scala
parsley/shared/src/main/scala/parsley/internal/deepembedding/frontend/Visitors.scala
parsley/shared/src/main/scala/parsley/internal/deepembedding/singletons/ErrorEmbedding.scala
parsley/shared/src/main/scala/parsley/internal/deepembedding/singletons/IntrinsicEmbedding.scala
parsley/shared/src/main/scala/parsley/internal/deepembedding/singletons/PrimitiveEmbedding.scala
parsley/shared/src/main/scala/parsley/internal/deepembedding/singletons/SequenceEmbedding.scala
parsley/shared/src/main/scala/parsley/internal/deepembedding/singletons/Singletons.scala
parsley/shared/src/main/scala/parsley/internal/deepembedding/singletons/TokenEmbedding.scala
parsley/shared/src/main/scala/parsley/internal/deepembedding/singletons/token/SymbolEmbedding.scala
parsley/shared/src/main/scala/parsley/internal/deepembedding/singletons/token/TextEmbedding.scala
parsley/shared/src/test/scala/parsley/internal/deepembedding/frontend/VisitorTests.scala

This PR adds the abstract classes `LazyParsleyIVisitor` and an abstract subclass `GenericLazyParsleyIVisitor` into the deep-embedding frontend. They are used for processing trees of `LazyParsley` parsers without needing to use manual exhaustive matching on `LazyParsley` types, which can be tedious to maintain if new `LazyParsley` subclasses are added. These visitors are also indexed, to preserve the generic return types of parsers while minimising uses of `.asInstanceOf[X]`.
However, all `LazyParsley` instances now have an additional requirement for a method, `visit`, which when given a visitor instance and a context argument, must call its respective `visit` method within the visitor. If a new `LazyParsley` subclass is added, a new `visit` method must be added to `LazyParsleyIVisitor` …

Add indexed Visitor classes for LazyParsley

---

project/ParsleySitePlugin.scala
project/plugins.sbt

Changes consist of:
* tweak imports for the new package structure
* adjust for config APIs which are no longer case classes for improved bincompat (e.g. `Versions`/`Version`)
* adjust for simplified `Formatter` API - see https://github.com/typelevel/Laika/pull/523 for details

update to sbt-typelevel 0.6.0-M1 with Laika 1.0.0-M5

---

parsley/shared/src/main/scala/parsley/Parsley.scala
parsley/shared/src/main/scala/parsley/exceptions/CorruptedReferenceException.scala
parsley/shared/src/main/scala/parsley/exceptions/UnfilledReferenceException.scala
parsley/shared/src/main/scala/parsley/internal/deepembedding/frontend/LazyParsley.scala
parsley/shared/src/main/scala/parsley/internal/diagnostics.scala
parsley/shared/src/main/scala/parsley/internal/machine/Context.scala
parsley/shared/src/main/scala/parsley/internal/machine/instructions/PrimitiveInstrs.scala
parsley/shared/src/main/scala/parsley/state.scala
parsley/shared/src/test/scala/parsley/token/SpaceTests.scala

Closes #232 by catching common errors and presenting them to the user in a more accessible way.

Add diagnostic information

---

docs/tutorial/effective-lexing.md

I coerced some of my students into trying out parsley. They seem to like it in general, but they missed the existence of the lexing API, and spend some time implementing their own lexer.
This tries to make the callout in the beginning more “in your face”.

Update effective-lexing.md to more clearly callout the lexing API

---

parsley/jvm-native/src/main/scala/parsley/PlatformSpecific.scala
parsley/shared/src/main/scala/parsley/Parsley.scala
parsley/shared/src/main/scala/parsley/exceptions/CorruptedReferenceException.scala
parsley/shared/src/main/scala/parsley/internal/deepembedding/backend/SequenceEmbedding.scala
parsley/shared/src/main/scala/parsley/internal/deepembedding/backend/StrictParsley.scala
parsley/shared/src/main/scala/parsley/internal/deepembedding/frontend/LazyParsley.scala
parsley/shared/src/main/scala/parsley/internal/diagnostics.scala
parsley/shared/src/main/scala/parsley/internal/machine/Context.scala
parsley/shared/src/main/scala/parsley/internal/machine/instructions/CoreInstrs.scala
parsley/shared/src/main/scala/parsley/internal/machine/instructions/PrimitiveInstrs.scala
parsley/shared/src/main/scala/parsley/state.scala
parsley/shared/src/test/scala/parsley/CoreTests.scala

`CalleeSave` is a problematic instruction that has possible race-conditions, as well as being badly behaved for recursively bound `flatMap`s. This system was designed to allow for references to reuse slots in the array when necessary. However, it is much safer to think of all the references in the universe being independent; the problem, of course, is that not all of these references are visible at the top-level, so there is likely not enough space to accommodate them.
This PR reworks things so that the `Context` feeds back information to a soon-to-be-generated `flatMap` body about the currently largest residency found for references. The `flatMap` will always allocate its references above this, and emit a new instruction that *just* resizes the refs array. 
It is possible that global …

New Reference Expansion

---

docs/tutorial/customising-error-messages.md

By the way, is there a shorthand for overriding the `DefaultErrorBuilder`'s `build` method, but keep all the implemented goodies?
```scala
class ErrBuilder extends DefaultErrorBuilder with ErrorBuilder[EnrichedErr] with MatchParserDemand {
override def build(pos: String, source: Option[String], lines: Seq[String]): MyError =
MyError(pos, source, lines)
}
```
The types are a bit awkward here, should I be using an implicit conversion here maybe?

fix(typo): new api for ErrorBuilder in 5.x

---

docs/api-guide/token/Lexer.md

fix(typo): out of place indent in lexer api guide

---

parsley-debug/shared/src/main/scala/parsley/debug/DebugTree.scala
parsley-debug/shared/src/main/scala/parsley/debug/internal/DebugContext.scala
parsley-debug/shared/src/main/scala/parsley/debug/internal/DivergenceContext.scala
parsley-debug/shared/src/main/scala/parsley/debug/internal/TransientDebugTree.scala
parsley-debug/shared/src/main/scala/parsley/internal/deepembedding/backend/debug/Tags.scala
parsley-debug/shared/src/main/scala/parsley/internal/deepembedding/frontend/debug/TaggedWith.scala
parsley-debug/shared/src/main/scala/parsley/internal/machine/instructions/debug/DebugInstrs.scala
parsley-debug/shared/src/test/scala/parsley/debug/DebuggerUsageSpec.scala
parsley-debug/shared/src/test/scala/parsley/debug/ReuseSpec.scala
parsley-debug/shared/src/test/scala/parsley/internal/deepembedding/RenameSpec.scala
parsley/shared/src/main/scala/parsley/internal/deepembedding/frontend/IterativeEmbedding.scala
parsley/shared/src/main/scala/parsley/internal/deepembedding/frontend/LazyParsley.scala
parsley/shared/src/main/scala/parsley/internal/deepembedding/frontend/Visitors.scala

Prior to these changes, there was no consistent way of identifying or handling parsers that performed iterative operations. This was problematic in scenarios where debugging needed to differentiate between parsers that may recurse in more complex ways (for example, chain or many-based parsers).
This PR introduces a new `Iterative` trait for chain/many-based combinators and modifies the `TaggedWith` infrastructure so that `isIterative` is properly propagated during debugging. It also introduces a `TaggingResult` case class for storing debug-related data in a more structured way.
Additionally, `DebugTree`, `TransientDebugTree`, and other files are updated to pass along this information, streamlining how iterative parsers are handled and improving the clarity of debug output.

Handle Looping Combinators with Tagging

---

parsley-debug/shared/src/main/scala/parsley/internal/deepembedding/frontend/debug/TaggedWith.scala

Fixes the code to compute bubbling of iterative let-bindings; it only approximates recursive bindings currently. A complete implementation would require knot-tying dataflow

Iterative Lets
